/**
 * Build-integrity tests.
 *
 * The client bundle is generated by scripts/build-client.mjs. These tests prove
 * the generator is byte-faithful for non-ASCII text (a lossy decode would ship
 * mojibake UI labels) and that its guards actually reject bad input instead of
 * silently emitting a broken bundle.
 */
import { execFileSync } from 'node:child_process'
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(root, 'src', 'client.js')
const OUT = join(root, 'lib', 'client.js')

let pass = 0
let fail = 0
const check = (name, cond, detail = '') => {
  if (cond) {
    pass++
    console.log(`  PASS  ${name}${detail ? ` — ${detail}` : ''}`)
  } else {
    fail++
    console.log(`  FAIL  ${name}${detail ? ` — ${detail}` : ''}`)
  }
}

const source = readFileSync(SRC, 'utf8')
const built = readFileSync(OUT, 'utf8')

console.log('== artifact is current ==')
try {
  execFileSync(process.execPath, [join(root, 'scripts', 'build-client.mjs'), '--check'], { cwd: root })
  check('lib/client.js matches src/client.js', true)
} catch {
  check('lib/client.js matches src/client.js', false, 'run node scripts/build-client.mjs')
}

console.log('\n== encoding fidelity ==')
const bytes = readFileSync(SRC)
try {
  new TextDecoder('utf-8', { fatal: true }).decode(bytes)
  check('src/client.js is valid UTF-8', true)
} catch (e) {
  check('src/client.js is valid UTF-8', false, e.message)
}
check('no BOM in src/client.js', !(bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf))
check('no replacement chars in the bundle', !built.includes('\uFFFD'))

// Every non-ASCII run from the source must appear verbatim in the bundle.
const runs = [...new Set(source.match(/[^\x00-\x7F]+/g) ?? [])]
const lost = runs.filter((s) => !built.includes(s))
check(`all ${runs.length} non-ASCII runs survive the build`, lost.length === 0, lost.slice(0, 3).join(' | '))

// Spot-check the user-visible labels that would be most embarrassing to lose.
for (const label of ['液态玻璃壁纸', '磨砂强度', '色彩浓度', '壁纸库', '使用中']) {
  check(`UI label intact: ${label}`, built.includes(label))
}

console.log('\n== bundle contract ==')
check('registers via __ModuleLoader__.load', built.startsWith('window.__ModuleLoader__.load({'))
check('registers the package id', built.includes('"dsh-liquid-glass-wallpaper"'))
check('exports apply', /exports\.apply\s*=/.test(built))
check('exports inject', /exports\.inject\s*=/.test(built))

console.log('\n== guards reject bad input ==')
const tmp = mkdtempSync(join(tmpdir(), 'lgw-build-'))
const backup = join(tmp, 'client.js')
copyFileSync(SRC, backup)

const expectThrow = (name, mutate, needle) => {
  try {
    const mutated = mutate(readFileSync(backup, 'utf8'))
    writeFileSync(SRC, mutated, 'utf8')
    let threw = null
    try {
      execFileSync(process.execPath, [join(root, 'scripts', 'build-client.mjs')], { cwd: root, stdio: 'pipe' })
    } catch (e) {
      threw = String(e.stderr ?? e.message)
    }
    check(name, threw !== null && (needle === null || threw.includes(needle)), threw ? threw.split('\n')[1]?.trim() : 'no throw')
  } finally {
    copyFileSync(backup, SRC)
  }
}

expectThrow('rejects a file with no exports', () => 'const x = 1\n', 'no exports found')
expectThrow('rejects an unconsumed export', (s) => `${s}\nconst y = 1\nexport { y }\n`, 'unconsumed')
expectThrow('rejects a duplicate export', (s) => `${s}\nexport const apply = 1\n`, 'duplicate export')

console.log('\n== restored ==')
rmSync(tmp, { recursive: true, force: true })
try {
  execFileSync(process.execPath, [join(root, 'scripts', 'build-client.mjs'), '--check'], { cwd: root, stdio: 'pipe' })
  check('source restored and rebuild is clean', true)
} catch {
  check('source restored and rebuild is clean', false, 'src/client.js was left modified!')
}

console.log(`\n${pass} passed, ${fail} failed`)
process.exit(fail === 0 ? 0 : 1)
